### PR TITLE
Add recipes / tests to get a running jekyll

### PR DESCRIPTION
**Pull request by schnitzeltony**
Am interested in jekyll. Most recipes could remain as auto-created - some required further tweaks (unshipped licenses / extra(-r)depends)
Unfortunately testimage fails all tests in my environment because dropbear's configuration files do not make it into rootfs. That causes passoword-less / root ssh accesses to fail for insufficient permission. Have to investigate further...
As an alternative test I simply use jekyll on target without issues for a while now - yeah good old manual testing....
So I hope this is acceptable for you (and your CI machinery).

### CODE REVIEW

**Comment by priv-kweihmann** [comment]
> some required further tweaks (unshipped licenses / extra(-r)depends)
that should be fine - on future package updates this info should be reused automatically as long as you always used these `EXTRA_[R]DEPENDS` vars (which is at first glance the case)

Let's see how these new recipes perform here in CI - I'm also willing to add exceptions for stuff that doesn't perform well in testing.
One thing that would be awesome if you could create some upstream tickets for the missing licenses - but that isn't a show stopper here

**Comment by priv-kweihmann** [comment]
And it seems like Github is once again doing some maintenance on a Sunday (so the pipelines are currently stuck for whatever reason) - if those are up and running within the next 2-3 hours, I'd kindly ask you to do a forced push to your current branch head to retrigger them

**Comment by priv-kweihmann** [comment]
@schnitzeltony please do a force push, CI seems to be back online

**Comment by priv-kweihmann** [comment]
Here are some finding from CI:
> jeventmachine should be loadable. ruby output: <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- java (LoadError)`

which means eventmachine depends on java gem.
 
> AssertionError: 1 != 0 : jekyll-sass-converter should be loadable. ruby output: /usr/lib/ruby/gems/3.0.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/source_map_page.rb:6:in `<module:Jekyll>': uninitialized constant Jekyll::Page (NameError)

still seems to be a different thing - could you please add an exception to https://github.com/priv-kweihmann/meta-rubygems/blob/master/lib/oeqa/runtime/cases/rubygems_exceptions.py for this module

**Comment by priv-kweihmann** [comment]
Also `packagegroup-rubygems.bb:5:warning:oelint.vars.dependsordered:'RDEPENDS_${PN}' entries should be ordered alphabetically` - could you please order the complete list once more - thx

**Comment by schnitzeltony** [comment]
> Also `packagegroup-rubygems.bb:5:warning:oelint.vars.dependsordered:'RDEPENDS_${PN}' entries should be ordered alphabetically` - could you please order the complete list once more - thx

This looks simple: Think it was rubygems-mercenary

> Here are some finding from CI:
> 
> > jeventmachine should be loadable. ruby output: internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- java (LoadError)`
> 
> which means eventmachine depends on java gem.

Looked into that: 
It seems there are two variants of eventmachine: One pure-ruby implementation and a JAVA wrapper (both using rubyeventmachine lib). See /usr/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/jeventmachine.rb initial comment:
```ruby
# This module provides "glue" for the Java version of the EventMachine reactor core.
# For C++ EventMachines, the analogous functionality is found in ext/rubymain.cpp,
# which is a garden-variety Ruby-extension glue module.

```

JAVA causes extra pain:
* It adds meta-java as dependency for meta-rubygems
* It requires a running native java with unknown environment
* Played around with meta-java a while back with no success

So my suggestion:
* on do_install remove /usr/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/jeventmachine.rb => Tests won't ask for java anymore
* Add a comment in recipe that JAVA is not supported
* patch /usr/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb for the unlikely case it detects JAVA (jruby?) to give a helpful error message that JAVA is not supported

What do you think?
<br/>
> 
> > AssertionError: 1 != 0 : jekyll-sass-converter should be loadable. ruby output: /usr/lib/ruby/gems/3.0.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/source_map_page.rb:6:in `module:Jekyll': uninitialized constant Jekyll::Page (NameError)
> 
> still seems to be a different thing - could you please add an exception to https://github.com/priv-kweihmann/meta-rubygems/blob/master/lib/oeqa/runtime/cases/rubygems_exceptions.py for this module

Will do

P.S.
To avoid running several iterations here I have to get my testimage environment working first (and as this is just for hobby => time is limited). So it may take a while till I come back with something better...

**Comment by priv-kweihmann** [comment]
> > Also `packagegroup-rubygems.bb:5:warning:oelint.vars.dependsordered:'RDEPENDS_${PN}' entries should be ordered alphabetically` - could you please order the complete list once more - thx
> 
> This looks simple: Think it was rubygems-mercenary
> 
> > Here are some finding from CI:
> > > jeventmachine should be loadable. ruby output: internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- java (LoadError)`
> > 
> > 
> > which means eventmachine depends on java gem.
> 
> Looked into that:
> It seems there are two variants of eventmachine: One pure-ruby implementation and a JAVA wrapper (both using rubyeventmachine lib). See /usr/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/jeventmachine.rb initial comment:
> 
> ```ruby
> # This module provides "glue" for the Java version of the EventMachine reactor core.
> # For C++ EventMachines, the analogous functionality is found in ext/rubymain.cpp,
> # which is a garden-variety Ruby-extension glue module.
> ```
> 
> JAVA causes extra pain:
> 
> * It adds meta-java as dependency for meta-rubygems

good lord, no - meta-java is one of the worst things I can remotely think off :-)

> * It requires a running native java with unknown environment
> * Played around with meta-java a while back with no success
> 
> So my suggestion:
> 
> * on do_install remove /usr/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/jeventmachine.rb => Tests won't ask for java anymore
> * Add a comment in recipe that JAVA is not supported
> * patch /usr/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb for the unlikely case it detects JAVA (jruby?) to give a helpful error message that JAVA is not supported
> 
> What do you think?

Yep, sounds right - I would be even happy without the patch - never heard of anyone that is actually using jruby in the OE sphere

> 
> 
> > > AssertionError: 1 != 0 : jekyll-sass-converter should be loadable. ruby output: /usr/lib/ruby/gems/3.0.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/source_map_page.rb:6:in `module:Jekyll': uninitialized constant Jekyll::Page (NameError)
> > 
> > 
> > still seems to be a different thing - could you please add an exception to https://github.com/priv-kweihmann/meta-rubygems/blob/master/lib/oeqa/runtime/cases/rubygems_exceptions.py for this module
> 
> Will do
> 
> P.S.
> To avoid running several iterations here I have to get my testimage environment working first (and as this is just for hobby => time is limited). So it may take a while till I come back with something better...

Same here :-) - but you can use the CI here anytime and spin up as many builds as you like

**Comment by schnitzeltony** [comment]
Seems CI runs did not start - is it due to weekend maintenance?

**Comment by priv-kweihmann** [comment]
> Seems CI runs did not start - is it due to weekend maintenance?

GitHub safety measures :-( (for you as a first time contributor, I have to enable each build manually) - seems like the builds are up and running

**Comment by schnitzeltony** [comment]
Thanks - hope to make it to second time contributor :)

**Comment by schnitzeltony** [comment]
As far as I can see the only thing still failing is alphabetical order in packagegroup-rubygems.bb. So I downloaded oelint-adv and added entries step by step and let oelint-adv test each change.

So last iteration (hopefully) for first time contributor please...

**Comment by priv-kweihmann** [comment]
@schnitzeltony do you need that for gatesgarth/dunfell too?

**Comment by schnitzeltony** [comment]
Would be cool - will do a test image on dunfell and report

**Pull request merged**
